### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by denyskonakhevych** [denyskonakhevych/Generics#1]
Dear Andrii,

Please provide your review of my tasks.

Many thanks!

**Comment by arodionov** [comment]
"Collection<T> rez = in.getClass().newInstance(); // TODO: is it correct?"
Of courese not!

Использование рефлекшена без крайней надобности считается очень плохим стилем. Пишите проще!

**Comment by denyskonakhevych** [comment]
В таком случае как можно вернуть экземпляр точно такой же коллекции, которую нам передали?

**Comment by arodionov** [comment]
А зачем возвращать экземпляр такой же коллекции? 
Вы гарантируете лишь то, что вернете что-то что имплементит Collection, и все.

**Comment by denyskonakhevych** [comment]
Я подумал, что правильнее было бы вернуть то же, что нам и передали. Например если пользователь пользовался LinkedList-ом, а мы ему вернем ArrayList, то у него могут быть потери производительности после этого.
Или это уже лишнее?

**Comment by arodionov** [comment]
Лишнее. Пользователь все равно не сможет воспользоваться преимуществами конкретной реализации без явного приведения типа.
По умолчанию возвращают ArrayList

**Comment by denyskonakhevych** [comment]
Хорошо, спасибо)
